### ISSUE TITLE
Error for ARDRegression

### ISSUE THREAD

**Issue by Mojzaar** [sdpython/mlinsights#116]
I was going to use PiecewiseRegressor with ARDRegression estimator but I am getting this error:

`Traceback (most recent call last):

  File "<ipython-input-37-ef69b6e34e02>", line 1, in <module>
    model.fit(sf.X_train,sf.y_train['powertransformer'])

  File "/usr/local/lib/python3.8/dist-packages/mlinsights/mlmodel/piecewise_estimator.py", line 250, in fit
    self.mean_estimator_ = clone(self.estimator).fit(X, y, sample_weight)

TypeError: fit() takes 3 positional arguments but 4 were given`

While PiecewiseRegressor works fine with other models like Ridge, Lasso and LinearRegression. Any idea what is going wrong here?

**Comment by sdpython** [comment]
I'm sorry. I don't actively work on this package. Do you have an example I could use to replicate the error?
